### ISSUE TITLE
This is Inappropriate Use of github

### ISSUE THREAD

**Issue by bakertaylor28** [alecmuffett/onion-sites-that-dont-suck#21]
Github is intended for software development AND IS NOT intended to merely operate as your private pastebin. This content needs to be removed /modified to contain legitimate source code, or it will be reported to Github for prompt removal.

**Comment by alecmuffett** [comment]
fixed.

**Comment by arashiyama** [comment]
People who upload JPG images shouldn't throw stones.

**Comment by mrkane27** [comment]
I see nothing at all in the terms of service that prevents this use case. Also, not a private pastebin if it's a public repo.

**Comment by francip** [comment]
@bakertaylor28 Github is a commercial entity selling hosted Git repositories with their @[Terms of Service](https://help.github.com/articles/github-terms-of-service/) ( [proposed changes to the ToS](https://help.github.com/articles/github-terms-of-service-draft/) ) as the main legal document defining the rights and liabilities of both sides in the transaction - Github and the user (@alecmuffett), as well as the acceptable use of the service.

> Github is intended for software development

Neither the current ToS nor the proposed changes define specific purposes for which their product shall be used. There are only few restrictions on the usage of service in the ToS, and none of them is mention anything about "software development".

> legitimate source code

Neither the current ToS nor the proposed changes define the type of material that shall be stored in the product they sell. There are only few restrictions on material that can be deemed illegal, harmful, or obscene, and none of these mention "source code".

Your claims above aim to substantially change the terms of a contract (as defined in the ToS and agreed upon during the account creation transaction) between Github and the user (@alecmuffett), to which you are not a signatory side. You have no legal standing to change the terms of a contract you are not a part of.

The only contract which terms you could attempt to amend is the contract between yourself and Github, defined by the same ToS. However, the ToS grants the right for changes to Github only. But even if you did have the rights to change the contract terms between you and Github, that is not something @alecmuffett can help you with.

Well, maybe he can and might even be willing, but it is unclear from your original post that this is your goal.

In any case, creating a modified ToS that covers your account only, and getting Github lawyers to agree to it is not a problem with the material in this particular repository. I would suggest creating a repository of your own, where you can keep your proposed ToS changes. If you make it public, other people could even contribute with some definitions of what material does and what does not constitute "source code" (seeing how the current ToS lacks such definition).

Disclaimer: I am not a lawyer, and nothing above shall be considered a legal advice. When it comes to legal matters, you should always consult a licensed legal professional.

**Comment by siddhant3s** [comment]
@bakertaylor28 Bruh! do you even gh-pages?
